name: Deploy to gh-pages

on:
  push:
    branches: [ main, revamp, models, tutorials, datasets ]
  pull_request:
    branches: [ main, revamp, models, tutorials, datasets ]
  repository_dispatch:
    types: [ update ]

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd utils
          pip install -r ./requirements.txt

      - name: Fetch model data
        run: |
          cd utils/models
          python get_models.py

      - name: Fetch tutorial data
        run: |
          cd utils/tutorials
          python3 fetch_tutorials.py
          python3 export_tutorials.py

      - name: Fetch datasets data
        run: |
          cd utils/datasets
          python get_datasets.py

      - name: Install and build
        run: |
          cd deepchem
          npm i --legacy-peer-deps
          npm run export
          cd out
          touch .nojekyll

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deepchem/out
          branch: gh-pages
          clean-exclude: |
            .nojekyll
            CNAME
