name: Deploy to gh-pages

on:
  push:
    branches: [ main, revamp, models ]
  pull_request:
    branches: [ main, revamp, models ]
  repository_dispatch:
    types: [ update ]

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3

      - name: Fetch model data
        run: |
          cd utils
          pip install -r ./requirements.txt
          python get_models.py

      - name: Install and Build
        run: |
          cd deepchem
          npm i --legacy-peer-deps
          npm run export
          cd out
          touch .nojekyll

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deepchem/out
          branch: gh-pages
          clean-exclude: |
            .nojekyll
            CNAME
